services:
  frontend:
    image: kennywu1007626240/quirknotes_frontend:latest
    ports:
      - "3000:3000"
    environment:
      - ENV=Docker
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
      target: backend
    image: kennywu1007626240/quirknotes_backend:latest
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"